version: '3.4'

services:
  webui:
    image: apicontractservice
    build:
      context: .
      dockerfile: src/WebUI/Dockerfile
  
    ports:
      - "5000:5000"
      - "5001:5001"
    
    restart: on-failure

  